import { useState } from 'react'
import {
  ArrowRight, Bus, Check, ChevronDown, CircleAlert, Clock3, Leaf,
  LocateFixed, LockKeyhole, Package, Route, Send, ShieldCheck,
  Sparkles, TrendingDown, Users, Wallet, X,
} from 'lucide-react'
import { BUS_FLEET, ROUTE_STOPS, STOPS } from './data/buses'
import { findMatches } from './services/routeMatcher'
import type { BusOption, ParcelStatus } from './types'
import './App.css'

type Page = 'overview' | 'send' | 'track' | 'operator' | 'receiver' | 'impact'
type Toast = { id: number; text: string; tone?: 'success' | 'info' }

const statusMeta: Record<ParcelStatus, { label: string; tone: string }> = {
  DRAFT: { label: 'DRAFT', tone: 'neutral' }, BOOKED: { label: 'BOOKED', tone: 'blue' },
  LOADED: { label: 'LOADED', tone: 'teal' }, IN_TRANSIT: { label: 'IN TRANSIT', tone: 'violet' },
  ARRIVING: { label: 'ARRIVING', tone: 'orange' }, ARRIVED: { label: 'ARRIVED', tone: 'orange' },
  READY_FOR_COLLECTION: { label: 'READY FOR COLLECTION', tone: 'green' }, DELIVERED: { label: 'DELIVERED', tone: 'green' },
}
const emptyForm = { sender: '', receiver: '', phone: '', pickup: 'Kopargaon Bus Stand', destination: 'Shirdi Bus Stand', type: 'Electronics', weight: '3', delivery: 'Fastest available' }

function App() {
  const [page, setPage] = useState<Page>('overview')
  const [form, setForm] = useState(emptyForm)
  const [matches, setMatches] = useState<BusOption[]>([])
  const [selected, setSelected] = useState<BusOption | null>(null)
  const [parcelStatus, setParcelStatus] = useState<ParcelStatus>('DRAFT')
  const [journeyStep, setJourneyStep] = useState(0)
  const [otp, setOtp] = useState('482716')
  const [otpInput, setOtpInput] = useState('')
  const [otpError, setOtpError] = useState('')
  const [toasts, setToasts] = useState<Toast[]>([])
  const [showWhy, setShowWhy] = useState<string | null>(null)

  const activeBus = selected?.bus ?? BUS_FLEET[0]
  const routeStart = activeBus.stops.indexOf(form.pickup)
  const routeEnd = activeBus.stops.indexOf(form.destination)
  const activeRouteStops = routeStart >= 0 && routeEnd >= routeStart ? activeBus.stops.slice(routeStart, routeEnd + 1) : ROUTE_STOPS
  const finalDestination = activeRouteStops[activeRouteStops.length - 1]
  const isBooked = parcelStatus !== 'DRAFT'
  const currentStop = activeRouteStops[Math.min(journeyStep, activeRouteStops.length - 1)]
  const nextStop = activeRouteStops[Math.min(journeyStep + 1, activeRouteStops.length - 1)]
  const progress = isBooked ? (journeyStep / (activeRouteStops.length - 1)) * 100 : 0
  const addToast = (text: string, tone: Toast['tone'] = 'success') => {
    const id = Date.now()
    setToasts((items) => [...items, { id, text, tone }])
    window.setTimeout(() => setToasts((items) => items.filter((item) => item.id !== id)), 4200)
  }
  const navigate = (target: Page) => { setPage(target); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const launchDemo = () => { setForm({ ...emptyForm, sender: 'Pratham', receiver: 'Rahul', phone: '98765 43210' }); setMatches([]); setSelected(null); setParcelStatus('DRAFT'); setJourneyStep(0); setOtp('482716'); setOtpInput(''); navigate('send'); addToast('Demo details loaded â€” find the best bus to begin.', 'info') }
  const resetDemo = () => { setForm(emptyForm); setMatches([]); setSelected(null); setParcelStatus('DRAFT'); setJourneyStep(0); setOtp('482716'); setOtpInput(''); setOtpError(''); navigate('overview'); addToast('Prototype simulation reset.', 'info') }
  const findBus = () => {
    const weight = Number(form.weight)
    if (!Number.isFinite(weight) || weight < 0.5 || weight > 20) { addToast('Enter a parcel weight between 0.5 and 20 kg.', 'info'); return }
    const ranked = findMatches(BUS_FLEET, form.pickup, form.destination, weight)
    if (!ranked.length) { addToast('No buses have enough cargo capacity for this parcel.', 'info'); return }
    setMatches(ranked); setSelected(ranked[0]); addToast(`${ranked[0].bus.id} is the strongest route match.`, 'info')
  }
  const confirm = () => { if (!selected) return; setParcelStatus('BOOKED'); setJourneyStep(0); setOtp(String(Math.floor(100000 + Math.random() * 900000))); addToast('Booking PL-2026-001 confirmed. Operator is ready to load it.') }
  const loadParcel = () => { if (parcelStatus !== 'BOOKED') return; setParcelStatus('LOADED'); addToast('Parcel PL-2026-001 has been loaded onto BUS-101.') }
  const startJourney = () => { if (parcelStatus !== 'LOADED') return; setParcelStatus('IN_TRANSIT'); addToast('BUS-101 has departed Kopargaon. Simulated GPS is now active.') }
  const advanceBus = () => {
    if (parcelStatus !== 'IN_TRANSIT' && parcelStatus !== 'ARRIVING') return
    const newStep = Math.min(journeyStep + 1, activeRouteStops.length - 1)
    setJourneyStep(newStep)
    if (newStep === activeRouteStops.length - 1) { setParcelStatus('READY_FOR_COLLECTION'); addToast(`BUS-101 reached ${finalDestination}. Parcel is ready for collection.`) }
    else if (newStep === activeRouteStops.length - 2) { setParcelStatus('ARRIVING'); addToast(`Your parcel is 18 minutes away from ${finalDestination}.`) }
    else addToast(`BUS-101 reached ${activeRouteStops[newStep]}.`, 'info')
  }
  const verify = () => { if (parcelStatus !== 'READY_FOR_COLLECTION') return; if (otpInput === otp) { setParcelStatus('DELIVERED'); setOtpError(''); addToast('OTP verified. Parcel delivered successfully!') } else setOtpError('That OTP does not match. Please try again.') }
  const shared = { activeBus, activeRouteStops, currentStop, nextStop, progress, parcelStatus, journeyStep, destination: finalDestination }

  return <div className="app-shell">
    <header className="topbar"><button className="brand" onClick={() => navigate('overview')} aria-label="ParcelLoop home"><span className="brand-mark"><Package size={19}/></span><span>Parcel<span>Loop</span></span></button><nav>{([['overview','Overview'],['send','Send Parcel'],['track','Track Parcel'],['operator','Operator'],['receiver','Receiver'],['impact','Impact']] as [Page,string][]).map(([key,label]) => <button className={page === key ? 'active' : ''} onClick={() => navigate(key)} key={key}>{label}</button>)}</nav><div className="head-actions"><span className="prototype"><span/> Prototype simulation</span><button className="ghost small" onClick={resetDemo}>Reset</button></div></header>
    <main>
      {page === 'overview' && <Overview onNavigate={navigate} onLaunch={launchDemo} />}
      {page === 'send' && <SendPage form={form} setForm={setForm} matches={matches} selected={selected} setSelected={setSelected} onFind={findBus} onConfirm={confirm} booked={isBooked} showWhy={showWhy} setShowWhy={setShowWhy} onOperator={() => navigate('operator')} />}
      {page === 'track' && <TrackPage {...shared} onSend={() => navigate('send')} />}
      {page === 'operator' && <OperatorPage {...shared} onLoad={loadParcel} onStart={startJourney} onAdvance={advanceBus} />}
      {page === 'receiver' && <ReceiverPage status={parcelStatus} otp={otp} input={otpInput} setInput={setOtpInput} error={otpError} destination={finalDestination} onVerify={verify} />}
      {page === 'impact' && <Impact delivered={parcelStatus === 'DELIVERED'} />}
    </main>
    <div className="toast-stack">{toasts.map((toast) => <div className={`toast ${toast.tone}`} key={toast.id}><Check size={16}/>{toast.text}<button onClick={() => setToasts((items) => items.filter((item) => item.id !== toast.id))}><X size={15}/></button></div>)}</div>
  </div>
}

function Overview({ onNavigate, onLaunch }: { onNavigate: (p: Page) => void; onLaunch: () => void }) { return <>
  <section className="hero-section"><div className="eyebrow"><Sparkles size={15}/> Smart Kopargaon Hackathon Â· Loop Crafters</div><div className="hero-grid"><div><h1>Deliver smarter with the buses <em>already on the road.</em></h1><p>ParcelLoop transforms unused public bus cargo capacity into an affordable, trackable parcel network.</p><div className="hero-actions"><button className="primary" onClick={() => onNavigate('send')}>Send a parcel <ArrowRight size={18}/></button><button className="secondary" onClick={() => onNavigate('track')}>Track parcel</button></div></div><div className="innovation-card"><span className="route-pill"><Bus size={17}/> Existing public bus</span><span className="equation">+</span><span className="route-pill"><Package size={17}/> Unused cargo capacity</span><div className="equals">=</div><strong>Low-cost parcel<br/>delivery network</strong><small>ParcelLoop is the coordination layer. The bus is the infrastructure.</small></div></div></section>
  <section className="metrics">{[[Bus,'12','Active buses'],[Package,'186 kg','Available cargo capacity'],[Route,'24','Parcels in transit'],[Check,'87','Deliveries today'],[Wallet,'â‚¹4,320','Cost saved']].map(([Icon,value,label], i) => <div className="metric" key={label as string}><span className={`metric-icon i${i}`}><Icon size={20}/></span><strong>{value as string}</strong><small>{label as string}</small></div>)}</section>
  <section className="how-section"><div><span className="section-label">HOW IT WORKS</span><h2>One bus ride. A complete delivery journey.</h2></div><button className="primary" onClick={onLaunch}><Sparkles size={17}/> Launch demo</button></section>
  <div className="steps">{[[Send,'1','Book','Tell us where the parcel needs to go.'],[Route,'2','Match','We rank buses already travelling there.'],[LocateFixed,'3','Track','Follow the simulated bus journey.'],[ShieldCheck,'4','Verify','Collect safely with an OTP.']].map(([Icon,num,title,text]) => <article key={title as string}><span className="step-number">{num as string}</span><span className="step-icon"><Icon size={23}/></span><h3>{title as string}</h3><p>{text as string}</p></article>)}</div>
</> }

function SendPage({ form, setForm, matches, selected, setSelected, onFind, onConfirm, booked, showWhy, setShowWhy, onOperator }: { form: typeof emptyForm; setForm: (x: typeof emptyForm) => void; matches: BusOption[]; selected: BusOption | null; setSelected: (b: BusOption) => void; onFind: () => void; onConfirm: () => void; booked: boolean; showWhy: string | null; setShowWhy: (x: string | null) => void; onOperator: () => void }) {
  const set = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: value })
  if (booked) return <section className="success-panel"><div className="success-icon"><Check size={36}/></div><span className="section-label">BOOKING CONFIRMED</span><h1>Parcel is in the loop.</h1><p>PL-2026-001 is booked on <b>{selected?.bus.id}</b>. Take it to Kopargaon Bus Stand for loading.</p><div className="booking-ticket"><span>Parcel ID<strong>PL-2026-001</strong></span><span>Route<strong>{form.pickup} â†’ {form.destination}</strong></span><span>Estimated delivery<strong>{selected?.bus.etaMinutes} minutes</strong></span></div><button className="primary" onClick={onOperator}>Proceed to operator dashboard <ArrowRight size={18}/></button></section>
  return <section className="page-grid send-grid"><div><span className="section-label">CUSTOMER Â· NEW DELIVERY</span><h1>Send a parcel on a route already moving.</h1><p className="lead">Find capacity on public busesâ€”no dedicated delivery vehicle required.</p><div className="form-card"><div className="form-title"><Package size={20}/> Parcel details</div><div className="fields"><Field label="Sender name" value={form.sender} onChange={(v) => set('sender',v)} placeholder="e.g. Pratham"/><Field label="Receiver name" value={form.receiver} onChange={(v) => set('receiver',v)} placeholder="e.g. Rahul"/><Field label="Phone number" value={form.phone} onChange={(v) => set('phone',v)} placeholder="98765 43210"/><Select label="Parcel type" value={form.type} onChange={(v) => set('type',v)} options={['Documents','Electronics','Clothing','Food Package','Medicine','Other']}/><Select label="Pickup stop" value={form.pickup} onChange={(v) => set('pickup',v)} options={STOPS}/><Select label="Destination stop" value={form.destination} onChange={(v) => set('destination',v)} options={STOPS}/><Field label="Parcel weight (kg)" value={form.weight} onChange={(v) => set('weight',v)} type="number"/><Select label="Preferred delivery" value={form.delivery} onChange={(v) => set('delivery',v)} options={['Fastest available','Lowest cost']}/></div><button className="primary full" onClick={onFind}>Find best bus <ArrowRight size={18}/></button></div></div>
    <div className="matches-side"><div className="side-title"><Route size={20}/><span>Route matching engine</span><small>Deterministic scoring</small></div>{matches.length === 0 ? <div className="empty-match"><div><Bus size={34}/></div><h3>Your best route is waiting.</h3><p>Enter a parcel and weâ€™ll compare route compatibility, capacity, time, and transfers.</p></div> : <div className="match-list">{matches.map((match, i) => <article className={`match-card ${selected?.bus.id === match.bus.id ? 'selected' : ''}`} key={match.bus.id}><div className="match-top"><span className={`badge ${i === 0 ? 'best' : i === 1 ? 'good' : ''}`}>{i === 0 ? 'BEST MATCH' : i === 1 ? 'GOOD MATCH' : 'ALTERNATIVE'}</span><span className="score">{match.score}% match</span></div><div className="bus-row"><span className="bus-icon"><Bus size={21}/></span><div><h3>{match.bus.id}</h3><p>{match.bus.routeLabel}</p></div></div><div className="bus-details"><span><Clock3 size={14}/>{match.bus.departureTime} Â· {match.bus.etaMinutes} min</span><span><Package size={14}/>{match.bus.availableCapacityKg} kg free</span><b>â‚¹{match.bus.price}</b></div><button className="why" onClick={() => setShowWhy(showWhy === match.bus.id ? null : match.bus.id)}>Why this bus? <ChevronDown size={16}/></button>{showWhy === match.bus.id && <ul className="why-list">{match.reasons.map((reason) => <li key={reason}><Check size={14}/>{reason}</li>)}</ul>}<button className={selected?.bus.id === match.bus.id ? 'selected-button' : 'select-button'} onClick={() => setSelected(match)}>{selected?.bus.id === match.bus.id ? <><Check size={16}/> Selected</> : 'Select bus'}</button></article>)}</div>}{selected && <div className="booking-bar"><div><small>Selected route</small><b>{selected.bus.id} Â· â‚¹{selected.bus.price}</b></div><button className="primary" onClick={onConfirm}>Confirm booking <ArrowRight size={17}/></button></div>}</div></section> }

function OperatorPage({ activeBus, activeRouteStops, currentStop, nextStop, progress, parcelStatus, destination, onLoad, onStart, onAdvance }: any) { const canAdvance = parcelStatus === 'IN_TRANSIT' || parcelStatus === 'ARRIVING'; return <section className="dashboard"><div className="dash-head"><div><span className="section-label">OPERATOR DASHBOARD</span><h1>{activeBus.id} <span>· {activeRouteStops.join(' -> ')}</span></h1></div><Status status={parcelStatus}/></div><div className="operator-layout"><RouteMap progress={progress} currentStop={currentStop} nextStop={nextStop} routeStops={activeRouteStops}/><aside className="journey-controls"><span className="gps"><LocateFixed size={15}/> SIMULATED GPS</span><h3>{parcelStatus === 'DRAFT' ? 'Waiting for booking' : currentStop}</h3><p>Next: <b>{nextStop}</b></p><div className="progress-line"><span style={{width:`${progress}%`}}/></div><div className="mini-stats"><span><small>Progress</small><b>{Math.round(progress)}%</b></span><span><small>Free cargo</small><b>{activeBus.availableCapacityKg} kg</b></span></div><div className="control-buttons"><button className="primary full" disabled={parcelStatus !== 'BOOKED'} onClick={onLoad}>Load parcel</button><button className="primary full" disabled={parcelStatus !== 'LOADED'} onClick={onStart}>Start journey <Bus size={17}/></button><button className="secondary full" disabled={!canAdvance} onClick={onAdvance}>Advance bus <ArrowRight size={17}/></button></div></aside></div><div className="parcel-table"><div className="table-head"><h2>Active parcels</h2><span>1 parcel</span></div><div className="parcel-row"><span className="parcel-box"><Package size={19}/></span><b>PL-2026-001</b><span>Electronics · 3 kg</span><span>Destination: {destination}</span><Status status={parcelStatus}/></div></div></section> }

function TrackPage({ activeBus, activeRouteStops, currentStop, nextStop, progress, parcelStatus, journeyStep, destination, onSend }: any) { const timeline: [ParcelStatus, string, string][] = [['BOOKED','Booking confirmed','Route matched with BUS-101'],['LOADED','Parcel loaded','Safely loaded at Kopargaon'],['IN_TRANSIT','Bus departed','BUS-101 is on its scheduled route'],['ARRIVING','Approaching destination',`Nearly at ${destination}`],['READY_FOR_COLLECTION','Ready for collection','OTP verification required'],['DELIVERED','Delivered','Collected successfully']]; const stage = (s: ParcelStatus) => ['DRAFT','BOOKED','LOADED','IN_TRANSIT','ARRIVING','ARRIVED','READY_FOR_COLLECTION','DELIVERED'].indexOf(s); if (parcelStatus === 'DRAFT') return <section className="empty-page"><Package size={38}/><h1>Track a parcel in the loop.</h1><p>Book a parcel first to see its live simulated journey.</p><button className="primary" onClick={onSend}>Send a parcel</button></section>; return <section className="dashboard"><div className="dash-head"><div><span className="section-label">PARCEL TRACKING</span><h1>PL-2026-001</h1><p>Electronics · 3 kg · BUS-101</p></div><Status status={parcelStatus}/></div><div className="tracking-layout"><div><RouteMap progress={progress} currentStop={currentStop} nextStop={nextStop} routeStops={activeRouteStops}/><div className="location-grid"><div><LocateFixed size={19}/><small>Current location</small><b>{currentStop}</b></div><div><Clock3 size={19}/><small>Estimated arrival</small><b>{parcelStatus === 'DELIVERED' ? 'Completed' : `${Math.max(0, 42 - journeyStep * 12)} min`}</b></div><div><Bus size={19}/><small>Bus</small><b>{activeBus.id} · {activeBus.operator}</b></div></div></div><div className="timeline">{timeline.map(([s,title,desc]) => <div className={stage(parcelStatus) >= stage(s) ? 'done' : ''} key={s}><i>{stage(parcelStatus) >= stage(s) ? <Check size={13}/> : ''}</i><span><b>{title}</b><small>{desc}</small></span></div>)}</div></div></section> }

function ReceiverPage({ status, otp, input, setInput, error, destination, onVerify }: any) { const ready = status === 'READY_FOR_COLLECTION'; const delivered = status === 'DELIVERED'; return <section className="receiver-page"><div className="receiver-card"><span className="section-label">RECEIVER DASHBOARD</span><div className="receiver-symbol"><Package size={36}/></div><h1>{delivered ? 'Parcel delivered.' : ready ? 'Your parcel has arrived.' : 'You have a parcel arriving.'}</h1><p>PL-2026-001 · From Kopargaon · Collect at {destination}</p><Status status={status}/>{ready && <><div className="otp-card"><span><LockKeyhole size={17}/> Pickup OTP</span><strong>{otp}</strong><small>Share this code with the bus operator at pickup.</small></div><label className="otp-entry">Enter OTP<input inputMode="numeric" maxLength={6} value={input} onChange={(e) => setInput(e.target.value.replace(/\D/g,''))} placeholder="000000"/></label>{error && <p className="form-error"><CircleAlert size={15}/>{error}</p>}<button className="primary full" onClick={onVerify}>Verify & collect <ShieldCheck size={17}/></button></>}{delivered && <div className="delivery-success"><Check size={21}/> OTP verified · safely collected</div>}{!ready && !delivered && <div className="receiver-wait"><Clock3 size={20}/><span>{status === 'DRAFT' ? 'Book the parcel to begin.' : 'We’ll notify you when it is ready for collection.'}</span></div>}</div></section> }

function Impact({ delivered }: { delivered: boolean }) { return <section className="impact-page"><div className="impact-intro"><span className="section-label">IMPACT DASHBOARD</span><h1>Every parcel rides on a trip <em>already happening.</em></h1><p>Prototype simulation estimates based on one ParcelLoop delivery.</p>{delivered && <span className="delivered-note"><Check size={15}/> Your delivery is included in these simulated totals</span>}</div><div className="impact-grid">{[[Wallet,'â‚¹80','Traditional delivery cost'],[TrendingDown,'â‚¹35','ParcelLoop cost'],[Wallet,'â‚¹45','Estimated savings'],[Leaf,'56%','Cost reduction'],[Route,'24','Dedicated trips avoided'],[Leaf,'18.4 kg','Estimated COâ‚‚ reduction']].map(([Icon,value,label],i) => <div className={`impact-card c${i}`} key={label as string}><Icon size={21}/><strong>{value as string}</strong><span>{label as string}</span></div>)}</div><div className="why-impact"><h2>Why ParcelLoop?</h2><div><article><Wallet size={20}/><b>Economic</b><p>Lower delivery cost and new revenue for transport operators.</p></article><article><Leaf size={20}/><b>Environmental</b><p>Fewer dedicated delivery vehicles on the road.</p></article><article><Users size={20}/><b>Social</b><p>Affordable delivery access for tier-2 and tier-3 towns.</p></article></div></div></section> }

function RouteMap({ progress, currentStop, nextStop, routeStops }: { progress: number; currentStop: string; nextStop: string; routeStops: string[] }) { const points = routeStops.map((_, i) => [70 + (630 * i / Math.max(1, routeStops.length - 1)), i === 1 ? 72 : i === 2 ? 64 : 103]); return <div className="route-map"><div className="map-top"><span><LocateFixed size={15}/> SIMULATED GPS</span><b>BUS-101</b></div><svg viewBox="0 0 760 180" role="img" aria-label={`Bus route from ${routeStops[0]} to ${routeStops[routeStops.length - 1]}. Current stop ${currentStop}, next ${nextStop}.`}><path className="route-base" d="M70 103 C160 40 220 145 320 96 S490 49 568 101 S655 130 700 64"/><path className="route-progress" style={{strokeDasharray:'850',strokeDashoffset:850-(850*progress/100)}} d="M70 103 C160 40 220 145 320 96 S490 49 568 101 S655 130 700 64"/>{points.map(([x,y],i) => <g key={routeStops[i]}><circle className={progress >= i/Math.max(1, routeStops.length - 1)*100 ? 'map-stop reached' : 'map-stop'} cx={x} cy={y} r="8"/></g>)}<g className="bus-marker" style={{transform:`translate(${70 + (630 * progress / 100)}px, ${102 - (38 * progress / 100)}px)`}}><circle r="17"/><foreignObject x="-10" y="-10" width="20" height="20"><div className="svg-bus"><Bus size={18}/></div></foreignObject></g></svg><div className="stop-labels">{routeStops.map((stop,i) => <span className={progress >= i/Math.max(1, routeStops.length - 1)*100 ? 'reached' : ''} key={stop}>{stop.replace(' Bus Stand','')}</span>)}</div></div> }
function Status({ status }: { status: ParcelStatus }) { const meta = statusMeta[status]; return <span className={`status ${meta.tone}`}>{meta.label}</span> }
function Field({ label, value, onChange, placeholder, type = 'text' }: { label: string; value: string; onChange: (x:string) => void; placeholder?: string; type?: string }) { return <label>{label}<input type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder}/></label> }
function Select({ label, value, onChange, options }: { label:string; value:string; onChange:(x:string)=>void; options:string[] }) { return <label>{label}<select value={value} onChange={(e) => onChange(e.target.value)}>{options.map((o) => <option value={o} key={o}>{o}</option>)}</select></label> }
export default App

